server:
  port: '9998'

spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  jpa:
    hibernate:
      ddl-auto: none #data init ?????? ?? create
    show-sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://127.0.0.1:3306/saleday}
    username: ${SPRING_DATASOURCE_USERNAME:saleday}
    password: ${SPRING_DATASOURCE_PASSWORD:saleday}
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:127.0.0.1}
      port: ${SPRING_DATA_REDIS_PORT:6379}

logging:
  level:
    org.hibernate.orm.connections.pooling: WARN #connection ???? warn ?? ?? ?? ??
