server:
  port: '9999'

spring:
  profiles:
    active: local
  jpa:
    hibernate:
      ddl-auto: create #data init 작성해두어서 일단 create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect #엔진 명시(명시하지 않으면, 잘못된 sql 인식될 수 있음)
        jdbc:
          batch_size: 1000
        order_inserts: true
        order_updates: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/saleday

logging:
  level:
    org.hibernate.orm.connections.pooling: WARN #connection 관련로그 warn 레벨 이상 부터 출력